apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/order-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: "3004"
        - name: DB_HOST
          value: "sb3.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "tqdqntkawh"
        - name: DB_NAME
          value: "sb3"
        - name: PRODUCT_API_URL
          value: "http://product-api:3002"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: order-api
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
