apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/product-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: DB_HOST
          value: "sb3.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "tqdqntkawh"
        - name: DB_NAME
          value: "sb3"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: S3_BUCKET
          value: "test1bipa-g3-u3"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: product-api
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
