apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommend-api
  template:
    metadata:
      labels:
        app: recommend-api
    spec:
      containers:
      - name: recommend-api
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/recommend-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: DB_HOST
          value: "sb3.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "tqdqntkawh"
        - name: DB_NAME
          value: "sb3"
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: recommend-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: recommend-api
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
